spring.application.name=organiflow


spring.profiles.active=dev


spring.mongodb.uri=mongodb+srv://leonelbarriosmay:leoncio123@cluster0.6a9v7do.mongodb.net/politicas_negocio?retryWrites=true&w=majority&authSource=admin
spring.mongodb.database=politicas_negocio
management.health.mongodb.enabled=false
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.security=TRACE
#logging.level.com.sw.organiflow=DEBUG

# Deshabilita la URL de ejemplo de Petstore al abrir Swagger
springdoc.swagger-ui.disable-swagger-default-url=true

app.jwt.secret=dev-secret-key-must-be-at-least-32-characters-long
# 10,800,000 ms = 3 horas
app.jwt.expiration=10800000

# Tu refresh token (actualmente en 7 días)
app.jwt.refresh-expiration=604800000
server.port=8001